name: pygtkhellosnap # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Example for developers # 79 char long summary
description: |
  This is snap for ubuntu with pygtk library.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots


apps:
  pygtkhellosnap:
    command: pygtkhellosnap
    plugs: [unity7, home, pulseaudio]

parts:
  pygtkhellosnap:
    plugin: python
    source: ./src
    stage-packages:
      - python3-gi
      - gir1.2-unity-5.0
      - gir1.2-notify-0.7
      - gir1.2-gtk-3.0
      - gir1.2-pango-1.0
    after: [desktop/gtk3]
